### ISSUE TITLE
Situational modifier not taken into account.

### ISSUE THREAD

**Issue by IrateRedKite** [Lazrius/FoundryVTT-Module-Active-Defence#3]
When making an active defence roll and adding a situational modifier using the provided dialogue, the roll doesn't take the modifier into account for the total roll. In some cases the modifier is recognized in the roll dialogue, but not actually added to the total! (See attached)

Roll with modifier and result:
![image](https://user-images.githubusercontent.com/12358715/158749242-45b978e5-4fc3-4a64-ba1b-8745358c5b4d.png)
![image](https://user-images.githubusercontent.com/12358715/158749308-c14b6c8e-cb7c-429b-8277-b38f7042cfca.png)

Roll with a dice modifier, appears but does not total:
![image](https://user-images.githubusercontent.com/12358715/158749165-d43bf001-92d6-411d-981e-345cf154620d.png)

You'll need to make sure the modifier applies for normal rolls, as well as those with advantage and disadvantage.

**Comment by Lazrius** [comment]
Fix packaged in 1.0.7 ([5142a91](https://github.com/Lazrius/FoundryVTT-Module-Active-Defence/commit/5142a91ab6c6beb03e996a683d7a0381d833b063))
